### ISSUE TITLE
cant not mount specific container

### ISSUE THREAD

**Issue by jerome-diver** [ovh/svfs#104]
### Context
- svfs version :0.8.2-1
- storage provider :hubic
- product :

### Steps to reproduce this issue :

1.mount command from README page with correct authentication, fur a specific container
2. contanier=default/Images (URL of contanier show this https://hubic.com/home/browser/#default/Images URL)

### Results you expected :
have my specific default/Images container mounted on my allready created directory. (i try to mount default, it works, so authentication  is ok, mountpoint is ok)

### Results you observed :
2016/11/04 20:41:28 mount helper error: fusermount: failed to access mountpoint /mnt/HUBIC/Images: Transport endpoint is not connected
FATA[2016-11-04T20:41:28+01:00] fusermount: exit status 1

### Debug log :
DEBU[2016-11-04T20:54:17+01:00] Skipping configuration : open : no such file or directory  source=svfs                                                                              
2016/11/04 20:54:17 mount helper error: fusermount: failed to access mountpoint /mnt/HUBIC/Images: Transport endpoint is not connected

### Additional information :
maybe my container tag name is wrong, could you please provide a real example for a given container other than default one (deeper) ?

**Comment by w3st3ry** [comment]
Hi,

Can you give me the exact command have you entered ?

Thx

**Comment by jerome-diver** [comment]
yes, exactly same as example from hubic.md file (with correct hubic_token and hubci_auth options) with: container=default/Images
when try for container=default, it works (but i not have a specific directory).

could you now be able to provide a real example (who works) for a container who target on a deeper directory than default one ? As i told you at the end, i think maybe the sentence of container was wrong... just provide an example and then, i should be able to check that.
thank you for read all my comment and for your help.

**Comment by xlucas** [comment]
Hello,

A container is like a top level directory, it's not part of a hierarchy. 

So `default/Images` is not a container. 
Instead, `default` is a container and `Images` is a pseudo directory.

If you want to create a new container, use your mount command without specifying the `container` option at all, then you'll see all containers under your account. After this, you can create a new one by simply adding a new top level directory (`mkdir /mountpoint/my_container`). 

Then you can also use it with the `container` option.

**Comment by jerome-diver** [comment]
@xlucas,
ok, i understand now.
thank you very much for explain me that, i didn't know.
