### ISSUE TITLE
svfs timeout with a statefull firewall in between

### ISSUE THREAD

**Issue by NainKult** [ovh/svfs#110]
### Context
- svfs version : svfs_0.9.0_amd64
- storage provider : ovh
- product : hubic

### Steps to reproduce this issue :
1. Mount an svfs partition
2. Put an agressive statefull NAT firewall in between (reproduced successfully with a pfSense VM)
3. Start an rsync job
4. Watch svfs trying to reuse a killed connections (mostly a SYN timeout)
5. Try to enter a command to end this madness between the debug lines (see below)
6. Watch your firewall logs getting filled with an infinite number of retries
7. Profit ??

### Results you expected :
svfs re-establishing a new TCP connection instead of trying to reuse an old one if it fails

### Results you observed :
svfs reusing a killed TCP connection, without being aware of it and do something about it

### Debug log :
  ```
Unsolicited response received on idle HTTP channel starting with HTTP/1.0 408 Request Time-out
Unsolicited response received on idle HTTP channel starting with HTTP/1.0 408 Request Time-out
Unsolicited response received on idle HTTP channel starting with HTTP/1.0 408 Request Time-out
[...] 
 ```
### Additional information :
Original problem happened on a debian host behind an OpenWRT (iptables based) statefull NAT firewall
Reproduced with an ubuntu host behind a pfSense (pf based) statefull NAT firewall because it has an aggressive way of closing TCP connections

Edit 1: Updated from 0.8.2 to 0.9.0
Edit 2: Confirmed not happening with a stateless NAT/Firewall

**Comment by xlucas** [comment]
Svfs's code is not using anything under OSI layer 7.

**Comment by Vad1mo** [comment]
I have the same issue. It seems to be cepth related. I happens also with docker registry running on ovh. 

https://github.com/docker/distribution/issues/1704
https://github.com/docker/distribution/issues/1673
http://tracker.ceph.com/issues/15812

**Comment by xlucas** [comment]
The issue was opened mentionning hubic as the target of the mountpoint thus a swift endpoint, not a swift gateway to ceph.

The log line you see is emitted by this line in the golang core : https://github.com/golang/go/blob/abdd73cc43f9187e8918879944ec0dacbc912b5c/src/net/http/transport.go#L1606 and AFAIA it's has no impact.

**Comment by Vad1mo** [comment]
As I understand Hubic and OVH Object Storage/Swift  in both cases there is cepth under the hood.

**Comment by xlucas** [comment]
Absolutely not.

* Hubic, Public Cloud Archive and Public Cloud Storage are running on pure Swift clusters.
* Cloud Disk Array is running on pure Ceph clusters.

There's no relationship between the two technologies involved in these offers.

**Comment by Vad1mo** [comment]
thank you for clarification
