### ISSUE TITLE
Mount svfs on OVH with allow_other options

### ISSUE THREAD

**Issue by ciciox** [ovh/svfs#112]
### Context
- svfs version : 0.9
- storage provider : OVH
- product : 

### Steps to reproduce this issue :

try to mount the fs using: 
mount -t svfs -o username=XXXXX,tenant=XXXX,password=XXXXX,region=GRA1,allow_other obj-backups-1 /mnt/obj-backups-1/

### Results you expected :
Every user can access to the folder mounted

### Results you observed :
just root is able to read and write in the mounted folder

### Debug log :

none
### Additional information :

i try to mount the fs with the script:

mount -t svfs -o username=XXXXX,tenant=XXXX,password=XXXXX,region=GRA1,allow_other obj-backups-1 /mnt/obj-backups-1/

as root i can get access and write files, but when i use another user im not able to get access to the folder.

how can i allow all users to access to the mountpoint?

**Comment by xlucas** [comment]
* Make sure your fuse installation allows using `allow_other` in `/etc/fuse.conf`.
* Add `default_perm=false` to your mount options in order to disable fuse's `default_permissions` feature. With this turned off the system won't check file ownership anymore.

**Comment by ciciox** [comment]
Hi,
i did as you explain,but something is still not working.
essentially after i mount svfs no one can get access to the folder a part root.
> root@s-backup-1:/home/admin# ls -l /mnt/
total 0
drwx------ 1 root root 4096 Dec 20 10:12 obj-backups-1

i checked the file `/etc/mtab `and i think that line is looking fine

`obj-backups-1 /mnt/obj-backups-1 fuse.svfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0`

i try to do chmod 777 on that folder but is not working

**Comment by xlucas** [comment]
It should work.

Either you use `default_perm=false` and then chmod is useless since permissions are not checked or you don't and use `mode=0777` instead.

What's your OS & fuse version ?

**Comment by ciciox** [comment]
Hi,
i mount svfs with
 `mount -t svfs -o username=XXX,tenant=XXX,password=XXX,region=GRA1,mode=0777, obj-backups-1 /mnt/obj-backups-1`

now the permissions are 777
```
root@s-backup-1:/home/admin# ls -l /mnt/obj-backups-1/obj-backups-1/
total 0
-rwxrwxrwx 1 root root 0 Dec 20 11:03 Bak_Config_
-rwxrwxrwx 1 root root 0 Dec 20 10:59 Bak_Config0053
```
but if i try to change the permissions i get the follow error
```
root@s-backup-1:/home/admin# chmod -R 777 /mnt/obj-backups-1/obj-backups-1
chmod: changing permissions of ‘/mnt/obj-backups-1/obj-backups-1/Bak_Config0053’: Operation not supported

```


essentially i need that the FS be able to write and read ( create and delete files ) with all users of my system.

What Options Can I use to achieve that?

**Comment by xlucas** [comment]
Again, *you can't chmod files in svfs* (it's not supported if you prefer) and permissions are set  *globally at mount time* with the `mode` option which in your case already set file & directory modes to `0777`.

So why are you trying to chmod it all over again ?

**Comment by xlucas** [comment]
Feel free to reopen with more information.
