### ISSUE TITLE
Mount SVFS on macOS Sierra

### ISSUE THREAD

**Issue by MaxNexo** [ovh/svfs#116]
### Context
- svfs version : 0.9.1
- storage provider : OVH
- product : hubiC
- macOS 10.12.1/10.12.2, FUSE for macOS 3.5.4, SSHFS 2.5.0.

### Steps to reproduce this issue :
1. Get token from hubic_application
2. Mount "OSXFUSE Volume 0 (svfs)" with sudo mount_svfs hubic /mountpoint -o hubic_auth=XXXX,hubic_token=XXXX,container=default,allow_other
3. Double click on "OSXFUSE Volume 0 (svfs)" or sudo cd /mountpoint.

### Results you expected :
View the content of the mounted volume.

### Results you observed :
Double clicking on the volume: Permission denied.
cd /mountpoint: Permission denied.
sudo cd /mountpoint: no effect.

### Additional information :
Tried to create the mount point folder at different locations and with different permissions but the result is still Permission denied.
There is only one user, who is also admin, on my computer.

Is there something I am missing or is it a bug/incompatibility?

Thank you for your help!

**Comment by xlucas** [comment]
Hello

Can you detail a bit the "sudo cd /mountpoint: no effect."* part ?

**Comment by MaxNexo** [comment]
After the mount_svfs command succeeded and the volume has been mounted, I typed in Terminal :
cd /mountpoint
=> Permission denied
sudo cd /mountpoint
=> no output from Terminal, the current path was not change to /mountpoint.


Le 6 janv. 2017 à 13:32, Xavier Lucas <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello

Can you detail a bit the "sudo cd /mountpoint: no effect."* part ?

**Comment by xlucas** [comment]
Can you copy/paste your console stream ? I don't really visualize this "no output" thing.

Regardless of that, you should pass your user `uid` and `gid` with mount options that have the same name, check [this section](https://github.com/ovh/svfs#access-restriction-options) of the documentation, and not use sudo after mounting.

**Comment by MaxNexo** [comment]
Here is the console stream:

mbp-de-maxime:~ Maxime$ cd /mountpoint
-bash: cd: /mountpoint: Permission denied

mbp-de-maxime:/ Maxime$ sudo cd /mountpoint
Password:
mbp-de-maxime:/ Maxime$

But anyway, it worked with the uid and gid (with or without allow_other) (but it didn't work with user_id and group_id).

Thank you very much for your help! I guess you can delete the issue since it was an issue at all...

Maxime

Le 6 janv. 2017 à 14:59, Xavier Lucas <notifications@github.com<mailto:notifications@github.com>> a écrit :


Can you copy/paste your console stream ? I don't really visualize this "no output" thing.

Regardless of that, you should pass your user uid and gid with mount options that have the same name, check this section<https://github.com/ovh/svfs#access-restriction-options> of the documentation, and not use sudo after mounting.
