### ISSUE TITLE
Mounting containers does not work

### ISSUE THREAD

**Issue by otnaida** [ovh/svfs#118]
Mounting containers does not work on debian

```
root@server-1:~# sudo mount -t svfs -o username=$OS_8k8axxx,password=$OS_T5qxxx,tenant=$OS_480xxx,region=$OS_BHS1 pcs /mountpoint
root@server-1:~# FATA[2017-01-16T10:36:13Z] Bad Request 
```
Thx

**Comment by xlucas** [comment]
Hello,

What are these $OS_xxxx you are using ?

**Comment by otnaida** [comment]
Using Openstack configuration file (openrc)

**Comment by xlucas** [comment]
Can you then show which variables you use instead of abbreviation ? Thanks

**Comment by otnaida** [comment]
sudo mount -t svfs -o username=$OS_8k8aGGfSNBjN,password=$OS_T5qFRRYfR7ENCqGTZgvGeybd54YMzafK,tenant=$OS_4801801713869114,region=$OS_BHS1 pcs /mountpoint

Thnks

**Comment by xlucas** [comment]
These variables does not exist in an openrc file.

 They are called OS_USERNAME, OS_TENANT_NAME, OS_PASSWORD and OS_REGION_NAME.

**Comment by otnaida** [comment]
Sorry, it's first time using linux. What's the correct way to write the variable?

Thanks

**Comment by xlucas** [comment]
Please read the readme [there](https://github.com/ovh/svfs#reading-credentials-from-the-environment) which describes multiple ways of using your openstack credentials with svfs (environment, mount option or configuration file).
