### ISSUE TITLE
How to access backups?

### ISSUE THREAD

**Issue by amauryhubault** [ovh/svfs#120]
Hi,

On macOS Sierra, I'd like to mount backups, how can I do? I installed svfs and set hubic_auth and hubic_token, but I can't manage to access it.

I put:
`sudo mount_svfs Essai1 /mountpoint -o hubic_auth=xxxx,hubic_token=xxxx,container=default`
but nothing happens.

Thanks for your answers

**Comment by xlucas** [comment]
Hello !

Backups are stored in separate containers alongside the `default` one. So just remove the `container=default` mount option and you will access all containers related to your account.

**Comment by amauryhubault** [comment]
Thanks for your answer. I did it, now I have a volume "OSXFUSE Volume 0 (svfs)”, but when I try to access it, I have this error : "The folder “OSXFUSE Volume 0 (svfs)” can’t be opened because you don’t have permission to see its contents."

**Comment by amauryhubault** [comment]
At least the system says it's the correct size of my hubic account :)

**Comment by xlucas** [comment]
Take a look at [access restriction mount options](https://github.com/ovh/svfs#access-restriction-options).
You probably want to pass `uid` and `gid` mount options or `default_perm=false`.
