### ISSUE TITLE
Read only ?

### ISSUE THREAD

**Issue by Tibo16** [ovh/svfs#124]
hi, 

I've mounted an OVH pCA without issue. I can read all files in container.
But, when i try "touch test" > "touch: setting times of ‘test’: Operation not supported"
BUT test file is fine created... So, i try to edit : nano test > Read only...
BUT echo test>test work fine, when i open test file, content = test.

Any help ?
Thanks !
Thibaut

**Comment by xlucas** [comment]
Hello,

Sounds pretty normal.

I guess in the first place you are not using the `attr` mount option so setting times on files won't work. 
As you know objects in PCA are locked for retrieval during a period of time after being uploaded. So they can't be read right away. However replacing a file doesn't imply reading its content so this will work.

**Comment by xlucas** [comment]
Feel free to reopen if you have any question.
