### ISSUE TITLE
The package doesn't list the files installed

### ISSUE THREAD

**Issue by kud** [ovh/svfs#125]
<img width="742" alt="image" src="https://cloud.githubusercontent.com/assets/655838/23716551/e5b9f836-0430-11e7-87ba-c51a01d1db0c.png">

**Comment by kud** [comment]
I would like to uninstall svfs but I don't know how because it's not listed by `pkgutil`.

**Comment by xlucas** [comment]
Hello,

Installed file are : 
```
/usr/local/bin/svfs
/usr/local/bin/mount_svfs
/usr/local/bin/hubic-application
```

**Comment by kud** [comment]
Thank you. :)

**Comment by kud** [comment]
I was interested by the project but reading `Moving directories.` made me afraid.

**Comment by xlucas** [comment]
@kud Just for information, mind to explain why ?

**Comment by kud** [comment]
Yeah sure.

I would like to find a way to mount my hubic storage. I don't like uploading files via my browser (because my files can be huge (like photo raw files)) and I don't want to use the synchronisation via hubic client because I don't want to let them on my local hard disk. I've tried cyberduck but it's not the best solution for me, I rather prefer a mounted virtual disk.

Plus the hubic webapp is too slow to move files and it can't create folders contrary to cyberduck.

**Comment by kud** [comment]
So I need a solution which allows me to upload files on hubic and erase them on my computer. I need to automatically create folders depending on what I upload. I need to be able to move files/folders quickly (moving files via hubic webapp is quite impossible for me, too slow :'().

**Comment by kud** [comment]
And something I dislike with cyberduck but it's maybe more an hubic problem. The token given to connect to cyberduck is reset at midnight. When you've got to upload more than 24h, it's really annoying.
