### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out

### ISSUE THREAD

**Issue by rdmendo** [ovh/svfs#127]
### Error
`Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>`

### Context
- svfs version :  0.9.1
- storage provider : OVH Private Storage
- product : Openstack swift
- command :
      mount.svfs  / $dest -o request_timeout=5m,connect_timeout=5m,segment_size=5120
- OS : debian  8.7 / ubuntu 16.04.02 / Centos 6.9 / Centos 7.3

### Steps to reproduce this issue :
tar cJPf $destitnation/$archive_file --atime-preserve --preserve-permissions --same-owner --acls --xattrs --selinux --exclude-caches $backup_files **(~ 1 to 6 GiB file)**
randomly append sometimes over 45 servers **(mostly when executed from cron task)**

**Comment by xlucas** [comment]
Check out #109
