### ISSUE TITLE
svfs.yaml not used for other options than hubic_token or hubic_auth

### ISSUE THREAD

**Issue by Notmarrco** [ovh/svfs#129]
### Context
- svfs version : 0.9.1
- storage provider :  hubic
- product : Debian 8.8

### Steps to reproduce this issue :
1. edit `/etc/svfs.yml` to add "uid=1000" and "gid=1000"
2. remove "uid=1000,gid=1000" from hubic fstab entry
3. `sudo mount hubic`

### Results you expected :
hubic should be mounted with the given uid and gid from `/etc/svfs.yaml`

### Results you observed :
hubic is mounted with owner `root:root` 

### Debug log :
nothing special

### Additional information :
`/etc/svfs.yml` already contains `hubic_token` and `hubic_auth` and it's used correctly.

**Comment by xlucas** [comment]
Hello, why are you setting mount options in svfs.yaml instead of fstab ?

This file should contain credentials, not mount options.

**Comment by Notmarrco** [comment]
I thought svfs.yaml was some "config file" for mounting svfs, since the hubic auth and token can be either specified in the fstab mount options or in the `svfs.yaml` file.

Ok, that makes sense, that way we can mount different containers in multiple places. (but it's limited to only one hubic instance though)

thx
