### ISSUE TITLE
Wrong perms with when using fstab

### ISSUE THREAD

**Issue by ColinChargy** [ovh/svfs#130]
Hello,
I run into the following :
### General information :
- svfs version : 0.9.1
- storage provider : hubic
- operating system : debian jessie

### Steps to reproduce this issue :
1. Add this to /etc/fstab :
/usr/local/bin/svfs /mnt/hubicCommun svfs       allow_other,user,hubic_auth=XXX,hubic_token=XXX       0       0
2. Refresh the mounting (umount if already mounted) :
sudo mount -a

### Results you expected :
I expect others users in this system to access the hubic folders.

### Results you observed :
I observe that only root can access the mounted hubic folder :
/mnt$ ls -lah
total 8.0K
drwxr-xr-x  3 root root 4.0K May 20 18:11 .
drwxr-xr-x 23 root root 4.0K Feb 12 22:02 ..
drwx------  1 root root 4.0K May 20 18:56 hubicCommun

/mnt$ cd hubicCommun/
-bash: cd: hubicCommun/: Permission denied

Please advice.
Best regards,
Colin Chargy

**Comment by spirann** [comment]
add "default_perm" and "mode" options

**Comment by ColinChargy** [comment]
Hi @spirann ,
I already had the mode option. Adding the default_perm solved the issue.

Thanks,
Best regards,
Colin Chargy
