### ISSUE TITLE
Removing via rm ./* -rf does throw Directory not empty

### ISSUE THREAD

**Issue by geNAZt** [ovh/svfs#132]
### Context
- svfs version : 0.9.1
- storage provider : OVH
- product : public cloud (openstack)

### Steps to reproduce this issue :

1. Reproduce issue #131 (copy the zip to a container)
2. Run rm ./* -rf in the mountpoint
3. You see "Directory not empty" errors

### Results you expected :
All folders and files deleted

### Results you observed :
It sometimes fails to clean the folders up and remove does detect files inside the folder i want to delete

**Comment by xlucas** [comment]
This is unfortunately a side effect of eventual consistency.
