### ISSUE TITLE
Would you please add proxy support?

### ISSUE THREAD

**Issue by netroby** [ovh/svfs#133]
We would like using svfs over the proxy , because we behind a firewall, but we can set up proxy , to let we cross the firewall.

Would you please provided us an proxy options to let us mount fs over proxy. like 

```
http_proxy=http://127.0.0.1:8123
```

**Comment by xlucas** [comment]
It sounds like the forked swift library already supports this (https://github.com/xlucas/swift/blob/master/swift.go#L265).
