### ISSUE TITLE
Option to ignore chmod and chown failure

### ISSUE THREAD

**Issue by spirann** [ovh/svfs#138]
It would be nice if we could use a parameter for chmod or chown to fail silently.
I know changing owner or access rights is not possible but some standard libraries like python's shutils.py try to chmod the file after a move for example. In this case chmod fails and so the shutils.py move function, even if the file is correctly copied to svfs.

ex: 
in move copy2(src, real_dst) File "/usr/lib/python2.7/shutil.py", line 131, in copy2 copystat(src, dst) File "/usr/lib/python2.7/shutil.py", line 100, in copystat os.chmod(dst, mode) OSError: [Errno 95] Operation not supported

**Comment by kayrus** [comment]
I'd suggest to cover all [limitations](https://github.com/ovh/svfs#limitations) here

**Comment by xlucas** [comment]
Do you mean "fail silently" ?

**Comment by kayrus** [comment]
jfyi: I made a [terrible hack](https://github.com/kayrus/svfs/commit/ec9bc4df0e6454af889bb04421674971940e9c93) for Java's [createNewFile](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createNewFile--) method. In my case this is quite safe, but for others this might be dangerous.

**Comment by xlucas** [comment]
The behavior is documented in the limitation section already.
