### ISSUE TITLE
Slow to add file

### ISSUE THREAD

**Issue by solisoft** [ovh/svfs#144]
I have a script which accept images and convert them on the fly 
https://resize.ovh/

The upload folder is a SVFS one ... delay are too high ... sometimes it takes 18s to put a file, sometimes it's under 1s ... very weird ... It's is ok to use it in production  ?

**Comment by solisoft** [comment]
Actually it's slow for read too
GET /r/988ac630-7f33-11e6-81cc-cf257bd2d626/1200/300 200 41683 - 51.823 ms
GET /r/94eef740-7f32-11e6-81cc-cf257bd2d626/400/350 200 42235 - 62.942 ms
GET /r/ac1907c0-7f33-11e6-81cc-cf257bd2d626/400/350 200 28964 - 41.818 ms
GET /r/b536ab10-7f32-11e6-81cc-cf257bd2d626/400/350 200 27980 - 83.334 ms
GET /r/24f956e0-7e76-11e6-96d5-b9e912b59939/350/300 200 18018 - 169.199 ms
GET /r/2e218c10-7e76-11e6-96d5-b9e912b59939/350/300 200 23699 - 187.967 ms
GET /r/12f86130-7fd8-11e6-81cc-cf257bd2d626/450/300 200 29592 - 1730.044 ms
GET /r/28d1f250-7fd8-11e6-81cc-cf257bd2d626/450/300 200 38763 - 1531.967 ms
GET /r/66d22390-7fd8-11e6-81cc-cf257bd2d626/450/300 200 38714 - 1609.679 ms
GET /r/b389e100-7fd8-11e6-81cc-cf257bd2d626/450/300 200 35611 - 14.061 ms
GET /r/be5d2e20-7fd8-11e6-81cc-cf257bd2d626/450/300 200 34852 - 25.828 ms
GET /r/37b9dd50-7fd8-11e6-81cc-cf257bd2d626/450/300 200 39493 - 1758.883 ms
GET /r/ef073310-d66b-11e6-b950-f98dc3215d0d/300/300 200 25674 - 11235.511 ms
GET /r/75f058c0-15e1-11e7-b950-f98dc3215d0d/300/300 200 28625 - 9767.227 ms

**Comment by xlucas** [comment]
Please provide additional information about the issue so there's something to dig on, like the product you are using, the region, the latency between your rig and the swift endpoint, your mount options and so on.
