### ISSUE TITLE
Problem with OVH Object Storage

### ISSUE THREAD

**Issue by dakser** [ovh/svfs#26]
Hi, I't looks like it's mounting the storage without any problem, but there's an issue when trying to create a file inside the container. I'm trying to create a simple txt with some text inside but I get this: 
"/mnt/swift-hls/test2.txt" E667: Fsync failed
WARNING: Original file may be lost or damaged
don't quit the editor until the file is successfully written!
Press ENTER or type command to continue

Any help is appreciated.

**Comment by xlucas** [comment]
Hello and thanks for reporting.
Are you somehow trying to edit that file directly in the filesystem ?
SVFS is an abstraction over object storage i.e. it will ultimately end up with REST calls to Swift which doesn't look like block storage. Thus writing to a file with an offset is not supported.
Take a look at the [limitations](https://github.com/ovh/svfs#limitations) section.

**Comment by dakser** [comment]
That's right! I have been able to copy a file from local file system to the OVH Object Storage. Maybe you could help me to know how to enable other users than root to create files inside the container, sorry for asking but I'm new with linux. Thanks in advance.

**Comment by dakser** [comment]
I hope that this additional info could help:
root@nginx:/home/admin# chown -R admin /mnt/swift-hls
root@nginx:/home/admin# ls -ld
drwxr-xr-x 5 admin admin 4096 Mar 10 21:20 .
root@nginx:/home/admin# ls -ld /mnt/swift-hls
drwx------ 1 root root 595332925 Mar 11 03:29 /mnt/swift-hls

**Comment by xlucas** [comment]
This case can be handled with [ownership options](https://github.com/ovh/svfs#ownership-options).

In your case you should use the `uid` of the admin user and the `gid` of your user group. Eventually you will need `mode=0770` to allow this group to read/write/traverse the container.

**Comment by dakser** [comment]
Thanks again Xavier.

**Comment by xlucas** [comment]
You're welcome !
