### ISSUE TITLE
mount: mounting {myname} on /hubic failed: No such device

### ISSUE THREAD

**Issue by ekozan** [ovh/svfs#27]
Hello 

I have a strange bug on my docker image when I run
`
svfs  -os-storage-url="https://lb1.hubic.ovh.net/v1/AUTH_{user}" -os-auth-token="{token}"  test /hubic &
`
it's work but if I do

`mount -t svfs -o token={token},storage_url=https://lb1.hubic.ovh.net/v1/AUTH_{user}  test /hubic`

it's say mount: mounting test on /hubic failed: No such device

any idea ?

**Comment by xlucas** [comment]
Hello,

Your second attempt should fail yielding the mount wrapper synopsis since option `-v` is not recognized.

Beyond this, can you post your whole dockerfile and your docker run command ?

**Comment by ekozan** [comment]
y the opt -v is a typing error ;) 

I run it on k8s so it's not exactly that 

`
docker run --privileged eko.ovh:5000/kube/backup:latest`
`
FROM alpine:3.3

COPY files /

RUN apk --no-cache add rsync fuse ca-certificates \
    && chmod +x /bin/svfs

VOLUME /backup
`

`
CGO_ENABLED=0 GOOS=linux go build --ldflags "-s" -o files/bin/svfs github.com/ovh/svfs
`

**Comment by xlucas** [comment]
You forgot to add the ruby package in your container.
Also make sure the `scripts/mount.svfs` is in `files/sbin/` before building your image.

**Comment by ekozan** [comment]
hoooo yeah your script is in ruby ... my bad

have you think about directly handle this with go ?

**Comment by xlucas** [comment]
Actually having dependencies is not a problem : all modern package managers handle this. I'd rather stick with a handy wrapper than completely break go flags conventions in order to implement an obsolete way of handling options.
