### ISSUE TITLE
svfs with synology

### ISSUE THREAD

**Issue by Plarkass** [ovh/svfs#31]
Hi,

I would like to use svfs to backup my datas from my synology NAS toward Hubic.
I try do do it by myself but i have not succeeded

So, i would like to know if you plan to do a .spk file to do that ?

Thanks !

**Comment by xlucas** [comment]
Hello !

We don't plan to provide a Synology Package for now, since [CloudSync](https://www.synology.com/en-global/knowledgebase/DSM/help/CloudSync/cloudsync) natively supports hubiC.
