### ISSUE TITLE
/mnt is not accessible: Transport endpoint is not connected

### ISSUE THREAD

**Issue by lvenier** [ovh/svfs#32]
I am using svfs to mount a container but when copying the data, aftyer few minutes I get : 
"/mnt is not accessible: Transport endpoint is not connected"

I will be also great to have df and du working.

**Comment by xlucas** [comment]
Hello !

The process is probably getting OOM killed. It happens on large trees if you don't customize mount options to fit your system specs.

You probably need to lower [`go_gc=<percent>`](https://github.com/ovh/svfs#performance-options) option. Using `50` as a start is a reasonable value, lower it if memory usage is still too high. Default is `100`.

The default value should be lowered around `50-60` in the next release.

**Comment by lvenier** [comment]
Thanks Xavier,

We have updated the mount option as follow :
mount -t svfs -o username=$OS_USERNAME,password=$OS_PASSWORD,tenant=$OS_TENANT_NAME,region=$OS_REGION_NAME,go_gc=50 NAS /mnt

We have then the following message :
E296: Seek error in swap file write: Illegal seek

Rgds

**Comment by xlucas** [comment]
Can you add details about steps leading you to this error ? It doesn't look like a syscall error.

**Comment by lvenier** [comment]
After a rsync command (aborted)

# rsync -av --delete ./fichiers/ /mnt/private/NAS2/OBJECTS/fichiers/

we can notice file with 0 size on target(/mnt) ; these files have content on the originator.

While trying to edit one of these zero filesize file, we catch this error message :

E296: Seek error in swap file write: Illegal seek

**Comment by xlucas** [comment]
You should take a look at the [FAQ](https://github.com/ovh/svfs/blob/master/docs/FAQ.md).
Keep in mind that svfs doesn't buffer operations in temporary files (it is fully connected) and is a layer of abstraction over object storage, **not block storage**. A direct consequence of this is that you can't edit a file with an offset : that operation can't be expressed to a valid HTTP request for a REST endpoint like Swift.

If you are using `rsync` you should adapt your flags to particularities of storing objects : you need to at least use `--inplace` and `-W` since rsync by default is working with blocks.

**Comment by xlucas** [comment]
Ok for closing ?

**Comment by lvenier** [comment]
Hi

Sorry for the late reply.
we have made the change as requested with the following command : 
rsync -avW --inplace --delete ./fichiers/ /mnt/fichiers/

but we still get errors after few minutes : 
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc82028dc80, 0x7f9611b447c8, 0xc82113d540)
  /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:417
created by github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve
    /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:420 +0x580

**Comment by lvenier** [comment]
we have a similar with cp instead of rsync. After few minutes he fails witht eh following message :

**Comment by lvenier** [comment]
goroutine 455904 [runnable]:
github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc82145a000, 0x7f8a020b6b60, 0xc8239e4dc0)
    /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:417
created by github.com/ovh/svfs/vendor/bazil.org/fuse/fs.(*Server).Serve
    /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/bazil.org/fuse/fs/serve.go:420 +0x580


goroutine 455284 [select]:
net/http.(*persistConn).roundTrip(0xc8239409c0, 0xc822d3e930, 0x0, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8200c00c0, 0xc821338540, 0xc8200c00c0, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc821338540, 0x7f8a05031550, 0xc8200c00c0, 0x0, 0x0, 0x0, 0xc8239408f0, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc820013cb0, 0xc821338540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc820013cb0, 0xc821338540, 0xa1ad90, 0x0, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc820013cb0, 0xc821338540, 0xc8288c8f90, 0x0, 0x0)
    /home/admin/.gvm/gos/go1.6/src/net/http/client.go:188 +0xff
github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).doTimeoutRequest.func1(0xc820084b40, 0xc821338540, 0xc827ba2c00)
    /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:224 +0x36
created by github.com/ovh/svfs/vendor/github.com/xlucas/swift.(*Connection).doTimeoutRequest
    /home/admin/.gvm/pkgsets/go1.6/global/src/github.com/ovh/svfs/vendor/github.com/xlucas/swift/swift.go:226 +0x8b

cp: cannot stat ‘./63099903’: Transport endpoint is not connected

**Comment by xlucas** [comment]
What part of the stacktrace is that ? Ca
