### ISSUE TITLE
MIME type of object

### ISSUE THREAD

**Issue by Gambiit** [ovh/svfs#33]
Hi,
Thanks for svfs : it's work fine. But...The MIME type is not set in the header "Content-type" of each objects. It's a problem when using the object storage through StaticWeb Middleware. How to fix it?

**Comment by xlucas** [comment]
Hello,

From a filesystem point of view, you obviously don't have this information, **but** there's apparently [an undocumented](https://github.com/openstack/swift/blob/d08ed1011d314e4d99abb21ec4e7d622b2ac827a/swift/proxy/controllers/obj.py#L551) feature for this in the Swift API: using `X-Detect-Content-Type` when uploading a file should force detection of content-type based on file extension (and only from that) from the swift object server.

I need to test this.

**Comment by Gambiit** [comment]
Nice : `X-Detect-Content-Type`. It's better than `Content-type`. But you have to apply on each object or just on the container storage?

**Comment by xlucas** [comment]
You need to set it on objects.

**Comment by xlucas** [comment]
`Content-Type` detection is now activated by default, you can pull 6d1ecb2 if you want to use it immediately.

It will be available in the next release and apply to new uploaded files only.
