### ISSUE TITLE
Is it possible to use allow_other to let others users access the files ?

### ISSUE THREAD

**Issue by peioe** [ovh/svfs#41]
I can't find how to use the allow_other option when using mount as root. 
And I also can't get it working with just "svfs options" instead of mount with hubic, could you explain how to do that ?

Thanks !

**Comment by xlucas** [comment]
Hello,

`allow_other` is hard set in svfs with `default_permissions`. This means files can only be accessed from other users using standard linux permissions checking (`uid`, `gid` and `mode` mount options) for now.

It makes sense to allow configuring this behaviour to honor fuse fs behaviours, so I will make these options available :

`allow_root=[true|false]` defaults to false
`allow_other=[true|false]` defaults to true
`default_permissions=[true|false]` defaults to true

Should be available soon :)

**Comment by peioe** [comment]
nice, thanks :)

**Comment by xlucas** [comment]
This will be available in the next release, you can already fetch the latest master branch to use it immediately.
