### ISSUE TITLE
Error 401 with Hubic

### ISSUE THREAD

**Issue by remyj38** [ovh/svfs#48]
Hi,

From many days, when I try to mount Hubic with svfs, I have this error :
> 2016/04/18 09:02:37 Invalid reply from server when fetching hubic API token : 401

I use this command : `mount -t svfs -o hubic_auth=https://lb1040.hubic.ovh.net/v1/AUTH_xyz123,hubic_token=mytoken123,container=default hubic /mnt/hubic
I use the 0.5.1 version on debian 7.10 x64`

**Comment by xlucas** [comment]
Hello,

When does this occur ? Right after trying to mount an svfs device or after some time ?

**Comment by remyj38** [comment]
Just after running the command

**Comment by xlucas** [comment]
Oh, I just get it. You are not using the right options.

Options `hubic_auth` and `hubic_token` are used once you registered an application in your hubic account (see the [docs](https://github.com/ovh/svfs/blob/master/docs/HubiC.md)).

On the other side, what you did is : you fetched a swift token and storage url from the hubic API, so options you are looking for are `token` and `storage_url` as described in the README.

**Comment by remyj38** [comment]
OK, it works. Thanks and sorry for the mistakes.

**Comment by xlucas** [comment]
No problem, you're welcome.

**Comment by widowild1** [comment]
i add a "application HubiC" and launch hubic-application 
`$  hubic-application 
Did you registered an application under your hubic account ? (y/N) y
 ~> Application redirect URL: http://localhost/             
 ~> Application client_id: api_hubic_Fy[...]
 ~> Application client_secret: 
1) Setting scope ... OK
 ~> Email: g9[...]@free.fr
 ~> Password: 
2) Granting access ... OK
3) Getting refresh token ... OK

 == Your mount options ==
 ~> hubic_auth=YXBpX[...]
 ~> hubic_token=3LFE[...]`

`$  sudo mount -t svfs -o hubic_auth=hubic_auth=YXBpX[...],hubic_token=3LFE[...],container=default hubic /home/wido/hubic/`
`wido ~ $  2016/04/24 11:19:47 Invalid reply from server when fetching hubic API token : 401`
`$  ls -al /home/wido/hubic 
ls: impossible d'accéder à '/home/wido/hubic': Noeud final de transport n'est pas connecté`
any idea?

**Comment by xlucas** [comment]
Make sure your authentication options are correct. Here your are using `hubic_auth=hubic_auth=...` which is wrong.

**Comment by widowild1** [comment]
lol tired...

**Comment by xlucas** [comment]
:)
