### ISSUE TITLE
you don't have the enough permission for watch the hubic content

### ISSUE THREAD

**Issue by cocodrino** [ovh/svfs#51]
Hi!!..I followed this guide https://github.com/ovh/svfs/blob/master/docs/HubiC.md and set my credentials, the cli return me the hubic_token and hubic_auth..then I try to run svfs

```bash
sudo mount -t svfs -o hubic_auth=YXBpX2h1YmljX3hBODg4eDFSdjZHYmt6x___secret____VUFFXOlZiZVJSd1VPd3NhS29SNUdoMk1JN3Fyc2I5dHRwODRUOTFQWkVBcWlCcDM4WXVuVnpZcEJPZGpKTThSdHNUNHg=,hubic_token=l8oyKv39Fv4Y0fp31dUiRC8mM___secret____zWvXZWWh2dgoSjgehlKcYyr60txv,container=default hubic /home/yo/Descargas/hubic

```

this mount the unit but when I try enter in it I get a message saying something like "you don't have the enough permission for watch the hubic content" (could not be exactly as this because I'm traslating it from spanish)

do you know what could be the problem here?
thank you so much!

**Comment by cocodrino** [comment]
hi..I followed this guide too
https://www.lowendtalk.com/discussion/78149/vfs-mount-on-hubic-pcs

now I mount the unit but when I try add a folder I get a message like "the folder xxxxxx can't be created because you don't have the destination's permission" or something like that (sorry for my translation).....

**Comment by xlucas** [comment]
Hello,

If you are mounting the filesystem as root with default options, then you need to be root to access it.

Now, options you need to set depend on how you want to grant users access to the filesystem. You can either use `uid` and `gid` options an set them to relevant values so linux permission checks will be used. Or you can set `default_perm=false` which maps to fuse's `default_permissions` option and that would allow all users to access the mountpoint without restriction.

These options are described in the [readme](https://github.com/ovh/svfs#ownership-options).

For both cases, make sure `user_allow_other` is not commented out in `/etc/fuse.conf`.

PS : the external guide (the latter one you quote) is deprecated, the first method you are using is the way to go.

**Comment by cocodrino** [comment]
thanks!!! default_perm=false did the job, now it works awesome!!
