### ISSUE TITLE
mount hubic over svfs on boot

### ISSUE THREAD

**Issue by Minims** [ovh/svfs#52]
Hello,

I've tried to mount my Hubic over svfs on boot with : 
 - Debian stretch amd64
 - Raspbian jessie (Pi 2)

 - All is OK on /etc/fstab.
 - "mount -a" once since is up and reachable is OK.

Mount fails on startup because network is unreachable to get credentials : 
Post https://api.hubic.com/oauth/token: dial tcp: lookup api.hubic.com on *:53: dial udp *: connect: network is unreachable

Thx

**Comment by jkaberg** [comment]
you can use ```_netdev``` in the /etc/fstab mount options to delay mounting until network is available or create a simple script in /etc/network/if-up.d/ (script will run when network is available) that mounts the svfs

**Comment by Minims** [comment]
_netdev option is working fine on my debian amd64.
But it doesn't on my Pi 2. 

mount[366]: Usage: mount.svfs dev dir [-o option=value,[option=value]...]
systemd[1]: home-pi-Hubic.mount mount process exited, code=exited status=1
systemd[1]: Failed to mount /home/pi/Hubic.
systemd[1]: Dependency failed for Remote File Systems.
systemd[1]: Unit home-pi-Hubic.mount entered failed state.

Once Pi is boot, mount -a is working fine. it may have a dependency problem, still searching

**Comment by jkaberg** [comment]
Try the other solution, make a script in /etc/network/if-up.d/ (make sure its has exection rights) that brings up your svfs

**Comment by xlucas** [comment]
Could you try using both options `x-systemd.automount` and `_netdev` ?

**Comment by Minims** [comment]
x-systemd.automount option has a problem. I can't mount my hubic with this one.

I've kept _netdev option only and put a script in /etc/network/if-up.d/hubic that just make a mount -a and it works fine.

Thx 👍

**Comment by jkaberg** [comment]
You could also just remove whatever you added in fstab and put this into the script instead,

```mount -t svfs -o username=..,password=..,tenant=..,region=..,container=.. myName /mountpoint```

Up to you ofcourse :smile:

**Comment by xlucas** [comment]
Closed due to inactivity.
