### ISSUE TITLE
Support for symlinks

### ISSUE THREAD

**Issue by xlucas** [ovh/svfs#62]
It would be better for svfs to support symlinks.

Implementation : In order to implement this feature, an other type of object should be added with `Content-Type: application/link`. A symlink target will be stored in a `Meta-Symlink-Target` header.

Restriction : a link should always reference an object within the same container. This should be documented in the limitations section.

**Comment by yadutaf** [comment]
Out of curiosity, is it a standard way to deal with links in Swift?

**Comment by xlucas** [comment]
As for now, there's no standard in Swift to handle symlinks.

AFAIK there is a [spec](https://review.openstack.org/gitweb?p=openstack/swift-specs.git;a=blob;f=specs/in_progress/symlinks.rst;h=4d722785a5c53bd48281c61c7b493fbc275169bd;hb=5a70b830afb7ad761006f915c3788270e035ec10) being reviewed that claims to bring *full* symlink support. It proposes handling symlinks as 0 byte objects containing a `X-Object-Symlink-Target-Object` header and ensure operation consistency between symlinks and referenced objects.

In the meantime, one could use Swift manifests, but they aren't true symlinks : operations on a manifest don't work the same way than they would do on referenced object. For instance, let's say you created an object which is a directory. If you create a manifest referencing this object and send a `GET` request on this one, then you will not get the list of objects in this directory as a result, but the content of all files that are inside, because manifests reassemble referenced objects. An other problem lays in object metadata that should be copied to the manifest with obviously the requirement to synchronize these when they change. Such an implementation would be unsuitable I believe since coming up with usage quirks outside `svfs`.

We take the choice here to make symlinks unusable outside `svfs`, since that's what they truly are.
