### ISSUE TITLE
Slow write speeds 

### ISSUE THREAD

**Issue by kozze89** [ovh/svfs#78]
### Context
- svfs version : 0.7.1
- storage provider : OVH
- product : Object storage
- server : OVH VPS-SSD-3
- connection : Capped at 100mbit (See speedtest result below) 

### Steps to reproduce this issue :

1. Mount with `svfs` command
2. `root@server-1:/mnt/ovh/# dd if=/dev/zero of=testfile2 bs=1k count=1M`
3. `root@server-1:/mnt/ovh/stoarme# dd if=testfile2 of=/tmp/testfile bs=1k count=1M`

### Results you expected :
I expect svfs to use the full (or close to it) capability of the server's connection.

### Results you observed :
Read speeds are in order, however the write speeds are bad. See debug log below.

### Debug log :
  ```
root@server-1:~/speedtest-cli# python speedtest_cli.py
 Retrieving speedtest.net configuration...
 Retrieving speedtest.net server list...
 Testing from OVH ({MY_OVH_IP_HERE})...
 Selecting best server based on latency...
 Hosted by FreeMobile (Paris) [1.88 km]: 7.821 ms
 Testing download speed........................................
 Download: 99.60 Mbit/s
 Testing upload speed..................................................
 Upload: 97.28 Mbit/s

 root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile2 bs=1k count=1M
 1048576+0 records in
 1048576+0 records out
 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 324.702 s, 3.3 MB/s

root@server-1:/mnt/ovh# dd if=testfile2 of=/tmp/testfile bs=1k count=1M
1048576+0 records in
1048576+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 85.2145 s, 12.6 MB/s
  ```

### Additional information :

1. I am curious what one can expect using svfs and OVHs object storage
2. Is the issue in svfs? Or in the object storage?
3. Have you tested this, if yes what speeds are you seeing?

**Comment by kozze89** [comment]
Just to add another test to this:

Ran another test on a server located in Paris. Some useful output. Mounted with the same command as above.
```
root@server-1:~# speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from XXX (XXXXXXX)...
Selecting best server based on latency...
b'Hosted by FreeMobile (Paris) [1.88 km]: 1.827 ms'
Testing download speed........................................
Download: 925.94 Mbit/s
Testing upload speed..................................................
Upload: 659.11 Mbit/s

root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile3 bs=1k count=1M
1048576+0 records in
1048576+0 records out
1073741824 bytes (1.1 GB) copied, 2576.15 s, 417 kB/s
```

I can run to the data center with a usb stick and upload data faster than 417kB/s and I live in Norway.

Any ideas how we can isolate the problem?

**Comment by nicodmf** [comment]
Same problem here : 

`
time dd if=/dev/zero of=testfile3 bs=1k count=100
100+0 enregistrements lus
100+0 enregistrements écrits
102400 octets (102 kB) copiés, 0,119684 s, 856 kB/s

real    0m41.224s
user    0m0.000s
sys     0m0.016s
`

**Comment by fejiso** [comment]
I'm pretty sure it's an OVH issue, the official hubiC client is limited to that range of speeds as well.

**Comment by kozze89** [comment]
I've now contacted OVH support on this, awaiting their response. I'll update this ticket once I get more information.

**Comment by xlucas** [comment]
@kozze89 Your benchmark is irrelevant. You are enforcing FUSE write requests size to `1kB`, whilst in a standard mode of operation, the kernel usually pick a value between `32kB` and `128kB`.

@nicodmf Either `dd` went crazy (unlikely) or you have a type somewhere. 41s to copy 102400 bytes at 856 kB/s doesn't make sense as an output.

@fejiso Hubic bandwith limitation doesn't apply to Public Cloud Storage.

**Comment by kozze89** [comment]
@xlucas Thanks for getting back to me. 

I wouldn't call my benchmark "irrelevant". But you do have a point indeed! see below results (done from same server in paris (not OVH) the 2016-06-30 around 2PM UTC). Also did the same test with the 1k base to compare and it seems to be twice as fast as last time, which suggest that milage may vary.

I am happy with this result and I will close this ticket for now. Will re-open if I start seeing issues with the speeds.

```
root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile4 bs=32k count=32500
32500+0 records in
32500+0 records out
1064960000 bytes (1.1 GB) copied, 69.2919 s, 15.4 MB/s

root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile4 bs=128k count=8125
8125+0 records in
8125+0 records out
1064960000 bytes (1.1 GB) copied, 44.2899 s, 24.0 MB/s

root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile4 bs=128k count=20000
20000+0 records in
20000+0 records out
2621440000 bytes (2.6 GB) copied, 78.2125 s, 33.5 MB/s


root@server-1:/mnt/ovh# dd if=/dev/zero of=testfile4 bs=1k count=1M
1048576+0 records in
1048576+0 records out
1073741824 bytes (1.1 GB) copied, 1002.95 s, 1.1 MB/s
```

**Comment by nicodmf** [comment]
@xlucas: i promess no typo in this test, i think about a not statically call for dd (a flush operation or other)

For now it's a little better : 

time dd if=/dev/zero of=testfile3 bs=1k count=10000
10000+0 enregistrements lus
10000+0 enregistrements écrits
10240000 octets (10 MB) copiés, 9,12356 s, 1,1 MB/s

real    0m9.132s
user    0m0.024s
sys     0m0.828s
