### ISSUE TITLE
Directory Date/Time

### ISSUE THREAD

**Issue by martinr92** [ovh/svfs#79]
### Context
- svfs version: 0.7.2
- storage provider: OVH
- product: hubic
### Steps to reproduce this issue:

I use hubic as the video storage for my personal media data. Now I tried to use svfs to mount hubic as a read only folder on my debian server.
Plex.tv is a great application to stream personal media data to many devices (iOS, android, smart tv, etc). But in combination with svfs, plex is really slow.

One of the major issues is, that plex continuously refreshes meta-data, because it detects a directory change.
Logfile from plex:

> DEBUG - Last refresh (2016-07-05 18:34:10) appears to be older than directory change time (2016-07-05 20:22:40), need to refresh local media agent.

A normal file storage doesn't use the current time as the directory timestamp.
### Expected behavior:

I know, that object storage doesn't have directories, but there should be more intelligence for this dates. A possible solution would be to set the date based on the items in it (using the latest date of the files within the directory).

Please let me know, if you need any more information.

Greetings,
Martin

**Comment by xlucas** [comment]
Hello,

Swift uses subdirectories : these can be either real objects or guessed from intermediate directories found within an object absolute path. And this latter case is the reason why it's not possible to implement directory modification time a persistent way.
