### ISSUE TITLE
Unable to mount svfs at boot time or with Ansible

### ISSUE THREAD

**Issue by jdesboeufs** [ovh/svfs#84]
### Context
- svfs version : 0.7.2 & 0.7.3
- storage provider : OVH
- product : Object Storage
- os : Ubuntu 14.04

### Steps to reproduce this issue :

1. Put this line in `/etc/fstab`
```
svfs_backups /mnt/backups svfs username=MY_USER,password=MY_PWD,tenant=MY_TENANT,region=GRA1,container=backups,uid=deploy,gid=deploy,auto 0 0
```
2. Reboot
3. Try to access to `/mnt/backups`

### Results you expected :

The directory should contain some files

### Results you observed :

The directory is empty (fs not mounted)

### Debug log :

I don't know how to find this using `/etc/fstab` at boot time.

### Additional information :

When I call `mount` directly, it works. When the system reboot, nothing happen.
When I use Ansible to call `mount`, I have this :
```
ls: cannot access /mnt/backups: Transport endpoint is not connected
```

**Comment by xlucas** [comment]
Hello,

Did you take a look at #52 ?

**Comment by jdesboeufs** [comment]
`x-systemd.automount` + `_netdev` => no changes

 I also tried with a script in `/etc/network/if-up.d/`:
```
#!/bin/sh
sleep 5
mount -t svfs -o username=XXX,password=XXX,tenant=XXX,region=GRA1,container=backups,uid=deploy,gid=deploy svfs_backups /mnt/backups
# Test Internet connection
curl http://perdu.com/ > /root/isup
```

=> Works fine two times out of three :(
(something mounted, sometimes not)

**Comment by jdesboeufs** [comment]
Is there a way to catch some logs on my use case?

**Comment by xlucas** [comment]
You can use the `debug` mount option and redirect stderr.

If you are running this exact ifup script, each interface will trigger this hook and you may be piling up mount calls, forcing svfs to call umount in the teardown process when the mountpoint isn't empty.

**Comment by jdesboeufs** [comment]
I hope ifup script will not be the final solution!

Now I'm using that:
```
#!/bin/sh

MOUNT_DIR=/mnt/{{item.name}}
FS_NAME=svfs_{{item.name}}

mkdir -p $MOUNT_DIR

umount $FS_NAME
mount -t svfs -o username={{svfs.userName}},password={{svfs.password}},tenant={{svfs.tenantName}},region={{svfs.regionName}},container={{item.container}},uid=deploy,gid=deploy $FS_NAME $MOUNT_DIR
```

When I reboot, it works!
When I call the script directly (with sudo), it works!

But when the script is called by Ansible, it fails silently and I get `ls: cannot access /mnt/backups/: Transport endpoint is not connected`.
I have finally added `sleep 30` at the end of the script, and now it's completely strange: while sleep is running, I can access to the container content, but when it's done, the error is back.

Any idea?

I just want to provision this mount point with Ansible, and be sure it keeps running, even after a reboot.

Thank you in advance.

(I'm ready to share the final Ansible role on GitHub and Ansible Galaxy)

**Comment by jdesboeufs** [comment]
After further investigation, in case of `mount` called through Ansible, the `svfs` process receive a SIGHUP and exit.

```
Process 8267 attached
epoll_wait(6, 7fff7b87e128, 128, -1)    = -1 EINTR (Interrupted system call)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_KERNEL} ---
rt_sigaction(SIGHUP, {SIG_DFL, ~[], SA_RESTORER|SA_STACK|SA_SIGINFO, 0x4628b0}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettid()                                = 8267
tkill(8267, SIGHUP)                     = 0
--- SIGHUP {si_signo=SIGHUP, si_code=SI_TKILL, si_pid=8267, si_uid=0} ---
+++ killed by SIGHUP +++
```

**Comment by xlucas** [comment]
You can try applying this patch to `/sbin/mount.svfs` : 

```patch
index 6226d87..e7015a8 100755
--- a/scripts/mount.svfs
+++ b/scripts/mount.svfs
@@ -10,7 +10,7 @@
 # *****************************************************************************
 
 if ENV['PATH'].nil?
-  ENV['PATH'] = "/bin:/usr/local/bin"
+  ENV['PATH'] = "/bin:/usr/bin:/usr/local/bin"
 end
 
 OPTIONS = {
@@ -73,4 +73,4 @@ if extra.empty?
   extra = "GOGC=60 "
 end
 
-system("#{extra}svfs #{opts.join(' ')} #{mount_dev} #{mount_dir} &")
+system("#{extra} nohup svfs #{opts.join(' ')} #{mount_dev} #{mount_dir} >/dev/null 2>&1 &")
```

**Comment by jdesboeufs** [comment]
Thx!

Now the `svfs` process survive but now it resists to `umount` and `fusermount -u`.

```
umount: /mnt/backups: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
```

But with `umount -f` it's OK!

**Comment by jdesboeufs** [comment]
With just `nohup` it works perfectly!
I continue to investigate and I will give you further feedback.

**Comment by jdesboeufs** [comment]
`/usr/bin` is important too.

**Comment by jdesboeufs** [comment]
My final Ansible role: [Gist](https://gist.github.com/jdesboeufs/8eba2b96846a39de5348e4846a4835ef)

For now `mount.svfs` file is hotfixed, but this step may be removed in the future.
